models.py
from exts import db
from datetime import datetime


class UserModel(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(64), nullable=False)
    password = db.Column(db.String(300), nullable=False)
    email = db.Column(db.String(64), nullable=False, unique=True)
    # phone = db.Column(db.String(64), nullable=False, unique=True)
    join_time = db.Column(db.DateTime, default=datetime.now)

class EmailCaptchaModel(db.Model):
    __tablename__ = 'email_captcha'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(64), nullable=False, unique=True)
    # phone = db.Column(db.String(64), nullable=False, unique=True)
    captcha = db.Column(db.String(64), default=datetime.now)

blueprints/forms.py
import wtforms
from wtforms.validators import Email, Length, EqualTo
from models import UserModel
from exts import redis_client

class RegisterForm(wtforms.Form):
    email = wtforms.StringField(validators=[Email(message="邮箱格式错误")])
    captcha = wtforms.StringField(validators=[Length(min=4, max=4, message="验证码格式错误！")])
    username = wtforms.StringField(validators=[Length(min=3, max=20, message="用户名格式错误！")])
    password = wtforms.StringField(validators=[Length(min=6, max=20,message="密码格式错误！")])
    #密码等于前面输入的密码
    password_confirm = wtforms.StringField(validators=[EqualTo("password", message="两次密码不一致！")])

    # 自定义验证：
    # 1.邮箱是否被注册
    def validate_email(self, field):
        email = field.data
        user = UserModel.query.filter_by(email=email).first()
        if user:
            raise wtforms.ValidationError(message="该邮箱以及被注册了！")

    # 2.验证码是否正确
    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        # Redis中获取验证码
        stored_captcha = redis_client.get(f"captcha:{email}")
        if not stored_captcha or stored_captcha.decode('utf-8') != captcha:
            raise wtforms.ValidationError(message="验证码错误或已过期")

app.py
from flask import Flask
import config
from exts import db, mail, redis_client
from models import UserModel
from blueprints.qa import bp as qa_bp
from blueprints.auth import bp as auth_bp
from flask_migrate import Migrate

app = Flask(__name__)
# 绑定配置文件
app.config.from_object(config)

# 初始化数据库和邮件
db.init_app(app)
mail.init_app(app)
redis_client.init_app(app)
migrate = Migrate(app, db)

# 注册蓝图
app.register_blueprint(qa_bp)
app.register_blueprint(auth_bp)


@app.route('/')
def hello_world():  # put application's code here
    return 'Hello World!'


if __name__ == '__main__':
    app.run()

blueprints/auth.py
import random
from flask import Blueprint, render_template, jsonify, redirect, url_for
from exts import mail, redis_client, db
from flask_mail import Message
from flask import request
import string
from .forms import RegisterForm
from models import UserModel
from werkzeug.security import generate_password_hash

bp = Blueprint("auth", __name__, url_prefix='/auth')


@bp.route('/login')
def login():
    pass


# GET：从服务器请求获取数据
# POST：将客户端的数据提交给服务器
@bp.route('/register', methods=['GET','POST'])
def register():

    if request.method == "GET":
        return render_template("register.html")
    else:
        # 验证用户提交的邮箱和验证码是否对应且正确
        # 验证用户输入的验证码和邮箱的是否对应
        # 表单验证：flask-wtf: wtfroms
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            # 创建一个新的用户实例，使用generate_password_hash方法对密码进行哈希处理。
            user = UserModel(username=username, email=email, password=generate_password_hash(password))
            # 将新创建的用户添加到数据库会话中。
            db.session.add(user)
            # 提交数据库会话，将新用户信息保存到数据库中。
            db.session.commit()
            # 重定向到登录页面。
            return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.register"))


@bp.route('/captcha/email')
def get_email_captcha():
    # /captcha/email/<email>
    # /captcha/email?email=xxx@qq.com
    email = request.args.get("email")
    if not email:
        return "缺少邮箱参数", 400

    # 验证码{4/6: 数组，字面，数组和字面的组合}
    source = string.digits * 4
    # 生成4位随机验证码
    captcha = ''.join(random.choices(source, k=4))

    # 创建邮件内容
    message = Message(
        subject="知了网站注册验证码！",
        recipients=[email],
        body=f"您的验证码是：{captcha}, 您正在通过邮箱登录【XXX的网站】，该验证码5分钟内有效，请勿泄露于他人。"
    )
    try:
        # 发送邮件
        mail.send(message)
        # 缓存验证码：memcached/redis
        email_captcha = redis_client.setex(f"captcha:{email}", 300, captcha)

        # 验证存储是否成功
        stored_captcha = redis_client.get(f"captcha:{email}")
        if stored_captcha:
            print(f"验证码成功存储: {stored_captcha}")
        else:
            print("验证码存储失败")


    except Exception as e:
        error_message = f"邮件发送失败: {str(e)}"
        print(error_message)  # 打印错误信息以便调试
        return error_message, 500

    print(f"验证码: {captcha}")  # 打印验证码以便调试
    # RESTful API
    # {code: 200/400/500, message: "", data: {}}
    return jsonify({"code": 200, "message": "", "data": None})


@bp.route('/mail/test')
def mail_test():
    try:
        message = Message(
            subject="邮箱测试",
            recipients=["3275594770@qq.com"],  # 确保邮箱地址正确
            body="Test"
        )
        mail.send(message)
        return "邮件发送成功"
    except Exception as e:
        error_message = f"邮件发送失败: {str(e)}"
        print(error_message)
        return error_message, 500


#测试是否连接上了redis
@bp.route('/test_redis')
def test_redis():
    try:
        redis_client.ping()
        return "Successfully connected to Redis"
    except Exception as e:
        return f"Error connecting to Redis: {e}"

blueprints/froms.py
import wtforms
from sqlalchemy.testing.pickleable import User
from wtforms.validators import Email, Length, EqualTo
from models import UserModel
from exts import redis_client


# From主要就是用来验证前端提交的数据是否符合数据
class RegisterForm(wtforms.Form):
    email = wtforms.StringField(walidators=[Email(message="邮箱格式错误！！！")])
    captcha = wtforms.StringField(validators=[Length(min=4, max=4, message="验证码格式错误！！！")])
    username = wtforms.StringField(validators=[Length(min=2, max=20, message="用户名格式错误！！！")])
    password = wtforms.StringField(validators=[Length(min=6, max=20, message="密码码格式错误！！！")])
    password_confirm = wtforms.StringField(validators=[EqualTo("password")])

    # 自定义验证：
    # 1. 邮箱是否被注册
    # 2. 验证码是否正确
    def validate_email(self, field):
        email = field.data
        user = UserModel.query.filter_by(email=email).first()
        if user:
            raise wtforms.ValidationError(message="该邮箱已经被注册")

    # 2. 验证码是否正确
    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        stored_captcha = redis_client.get(f"captcha:{email}")
        if not stored_captcha or stored_captcha != captcha:
            raise wtforms.ValidationError(message="验证码错误或已过期")

blueprints/qa.py
from flask import Blueprint

bp = Blueprint('qa', __name__, url_prefix='/')


@bp.route('/')
def index():
    return "QA Index Page"


@bp.route('/public_qa')
def public_qa():
    return "Public QA Page"


@bp.route('/search')
def search():
    return "Search Page"

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for("static",filename="bootstrap/bootstrap.4.6.min.css") }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    {% block head %}

    {% endblock %}
    <title>{% block title %}

    {% endblock %}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">知了问答</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("qa.public_qa") }}">发布问答</a>
                </li>
                <li class="nav-item ml-2">
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for("qa.search") }}">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search"
                               name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <span class="nav-link">{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.logout") }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.login") }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.register") }}">注册</a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block body %}
    {% endblock %}
</div>

</body>

</html>

templates/detail.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for("static",filename="css/detail.css") }}">
{% endblock %}
{% block title %}
    {{ question.title }}
{% endblock %}


{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10" style="background-color: #fff;padding: 20px;">
            <h3 class="page-title">{{ question.title }}</h3>
            <p class="question-info">
                <span>作者：{{ question.author.username }}</span>
                <span>时间：{{ question.create_time }}</span>
            </p>
            <hr>
            <p class="question-content">{{ question.content }}</p>
            <hr>
            <h4 class="comment-group-title">评论（{{ question.answers |length }}）：</h4>
            <form action="{{ url_for("qa.answer_public") }}" method="post">
                <div class="form-group">
                    <input type="text" placeholder="请填写评论" name="content" class="form-control">
                    <input type="hidden" name="question_id" value="{{ question.id }}">
                </div>
                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary">评论</button>
                </div>
            </form>
            <ul class="comment-group">
                {% for answer in question.answers %}



                    <li>
                        <div class="user-info">
                            <img class="avatar" src="{{ url_for("static",filename="images/avatar.jpg") }}" alt="">
                            <span class="username">{{ answer.author.username }}</span>
                            <span class="create-time">{{ answer.create_time }}</span>
                        </div>
                        <p class="comment-content">{{ answer.content }}</p>
                    </li>

                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for("static",filename="css/index.css") }}">
{% endblock %}
{% block title %}
    首页
{% endblock %}
{% block body %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for question in questions %}



                    <li>
                        <div class="side-question">
                            <img class="side-question-avatar" src="{{ url_for("static",filename="images/avatar.jpg") }}"
                                 alt="">
                        </div>
                        <div class="question-main">
                            <div class="question-title"><a
                                    href="{{ url_for("qa.qa_detail",qa_id=question.id) }}">{{ question.title }}</a>
                            </div>
                            <div class="question-content">{{ question.content }}</div>
                            <div class="question-detail">
                                <span class="question-author">{{ question.username }}</span>
                                <span class="question-time">{{ question.create_time }}</span>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}
    乘风-登录
{% endblock %}
{% block head %}
    <script>
        function validateEmail() {
            var email = document.getElementById("email").value;
            var error = document.getElementById("error");

            // 正则表达式验证邮件地址是否符合标准
            var emailRegex = /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(\.[a-zA-Z0-9_-])+/
            if (!emailRegex.test(email)) {
                error.innerHTML = "请输入有效的邮件地址";
                return false;
            }

            // 验证邮件地址是否为空
            if (email == "") {
                error.innerHTML = "邮件地址不能为空";
                return false;
            }

            // 验证通过，清空错误提示信息
            error.innerHTML = "";
            return true;
        }
    </script>
{% endblock %} }
{% block body %}
    <div class="container">
        <div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endwith %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                               name="email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

templates/public_question.html
{% extends "base.html" %}
{% block title %}
    发布问答
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <h1 style="text-align: center;">发布问答</h1>
            <form action="#" method="post">
                <div class="form-group">
                    <input type="text" name="title" class="form-control" placeholder="请输入标题">
                </div>
                <div class="form-group">
                    <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
                </div>
                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary">发布</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/register.html
 {% extends "base.html" %}

{% block head %}
    <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/register.js') }}"></script>
    <script>
        function validateEmail() {
            var email = document.getElementById("email").value;
            var error = document.getElementById("error");

            // 正则表达式验证邮件地址是否符合标准
            var emailRegex = /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(\.[a-zA-Z0-9_-])+/
            if (!emailRegex.test(email)) {
                error.innerHTML = "请输入有效的邮件地址";
                return false;
            }

            // 验证邮件地址是否为空
            if (email == "") {
                error.innerHTML = "邮件地址不能为空";
                return false;
            }

            // 验证通过，清空错误提示信息
            error.innerHTML = "";
            return true;
        }
    </script>
{% endblock %}

{% block title %}
    知了问答平台-注册
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    <div id="error"></div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>

                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                               name="email" required>

                        <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">验证码</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="captcha">

                            <div class="input-group-append">

                                <button class="btn btn-outline-secondary" type="button" id="captcha-btn" >获取验证码
                                </button>

                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">用户名</label>
                        <input type="text" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">确认密码</label>
                        <input type="password" class="form-control" name="password_confirm">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">立即注册</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}